CREATE TABLE WEB_SCHOOL_DEPTS (
    DEPT_NO NUMBER(3) PRIMARY KEY,
    DEPT_NAME VARCHAR2(100) NOT NULL
);

INSERT INTO WEB_SCHOOL_DEPTS VALUES(101, '컴퓨터공학과');
INSERT INTO WEB_SCHOOL_DEPTS VALUES(102, '전자공학과');
INSERT INTO WEB_SCHOOL_DEPTS VALUES(103, '기계공학과');
INSERT INTO WEB_SCHOOL_DEPTS VALUES(104, '전기공학과');

CREATE TABLE WEB_SCHOOL_STUDENTS (
  STUDENT_ID VARCHAR2(20) PRIMARY KEY,
  STUDENT_PASSWORD VARCHAR2(20) NOT NULL,
  STUDENT_NAME VARCHAR2(100) NOT NULL,
  STUDENT_GRADE NUMBER(1) NOT NULL,
  STUDENT_UPDATE_DATE DATE DEFAULT SYSDATE,
  STUDENT_CREATE_DATE DATE DEFAULT SYSDATE,
  DEPT_NO NUMBER(3) REFERENCES WEB_SCHOOL_DEPTS (DEPT_NO)
);

CREATE TABLE WEB_SCHOOL_PROFESSORS (
  PROFESSOR_ID VARCHAR2(20) PRIMARY KEY,
  PROFESSOR_PASSWORD VARCHAR2(20) NOT NULL,
  PROFESSOR_NAME VARCHAR2(100) NOT NULL,
  PROFESSOR_POSITION VARCHAR2(20) NOT NULL,
  PROFESSOR_UPDATE_DATE DATE DEFAULT SYSDATE,
  PROFESSOR_CREATE_DATE DATE DEFAULT SYSDATE,
  DEPT_NO NUMBER(3) REFERENCES WEB_SCHOOL_DEPTS (DEPT_NO)
);

CREATE TABLE WEB_SCHOOL_COURSES (
  COURSE_NO NUMBER(4) PRIMARY KEY,
  COURSE_NAME VARCHAR2(255) NOT NULL,
  COURSE_TYPE VARCHAR2(20) NOT NULL,
  COURSE_SCORE NUMBER(1),
  COURSE_QUOTA NUMBER(3),
  COURSE_REQ_CNT NUMBER(3),
  COURSE_DESCRIPTION VARCHAR2(1000),
  COURSE_UPDATE_DATE DATE DEFAULT SYSDATE,
  COURSE_CREATE_DATE DATE DEFAULT SYSDATE,
  DEPT_NO NUMBER(3) REFERENCES WEB_SCHOOL_DEPTS (DEPT_NO),
  PROFESSOR_ID VARCHAR2(20) REFERENCES WEB_SCHOOL_PROFESSORS (PROFESSOR_ID)
);

CREATE TABLE WEB_SCHOOL_REGISTRATIONS (
    REG_NO NUMBER(4) PRIMARY KEY,
    COURSE_NO NUMBER(4) REFERENCES WEB_SCHOOL_COURSES (COURSE_NO),
    STUDENT_ID VARCHAR2(20) REFERENCES WEB_SCHOOL_STUDENTS (STUDENT_ID),
    REG_STATUS VARCHAR2(20) DEFAULT '신청완료',
    REG_UPDATE_DATE DATE DEFAULT SYSDATE,
    REG_CREATE_DATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE WEB_SCHOOL_COURSES_SEQ START WITH 1000;
CREATE SEQUENCE WEB_SCHOOL_REG_SEQ START WITH 5000;